Repository DeveloperAcademy-POSTECH/MacC-Team-Spacer, pull requests merged in 2022-11, with the labels that each got.

#38 [FEAT] #37 Update VisualTagCalendarView color & layout
  Spacer/Spacer/Views/VisualTagView/Calendar/CalenderCell/CustomCalenderCell.swift
  Spacer/Spacer/Views/VisualTagView/Calendar/VisualTagCalendarViewController.swift
Labels: 🐯 오션, 🎨 Design, ⭐️ Feature

#41 [FEAT] 데이터 구조 수정 및 데이터를 사용하는 전체 파일의 데이터 관련 코드 수정
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer/Assets.xcassets/eventElement/eventElementHBanner.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/eventElement/eventElementHBanner.imageset/eventElementHBanner 1.png
  Spacer/Spacer/Assets.xcassets/eventElement/eventElementHBanner.imageset/eventElementHBanner 2.png
  Spacer/Spacer/Assets.xcassets/eventElement/eventElementHBanner.imageset/eventElementHBanner.png
  Spacer/Spacer/Assets.xcassets/eventElement/eventElementXBanner.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/eventElement/eventElementXBanner.imageset/eventElementXBanner 1.png
  Spacer/Spacer/Assets.xcassets/eventElement/eventElementXBanner.imageset/eventElementXBanner 2.png
  Spacer/Spacer/Assets.xcassets/eventElement/eventElementXBanner.imageset/eventElementXBanner.png
  Spacer/Spacer/Cores/BirthdayCafeView/BirthdayCafeViewController.swift
  Spacer/Spacer/Cores/BirthdayCafeView/PopularCafeTableViewCell.swift
  Spacer/Spacer/Cores/BirthdayCafeView/RecentCafeCollectionViewCell.swift
  Spacer/Spacer/Cores/BirthdayCafeView/RecentCafeTableViewCell.swift
  Spacer/Spacer/Model/CafeInfo.swift
  Spacer/Spacer/Model/CafeInfoData.json
  Spacer/Spacer/Model/CafeInfoModel.swift
  Spacer/Spacer/Model/MockParser.swift
  Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
  Spacer/Spacer/Views/CafeDetailView/DetailInfomationViewController.swift
  Spacer/Spacer/Views/SearchListView/ResultCollectionViewCell.swift
  Spacer/Spacer/Views/SearchListView/SearchListViewController.swift
Labels: 🐯 랑, 🎨 Design, ⭐️ Feature, 💾 Data

#46 [FEAT] 공통적으로 사용되는 아이콘 이미지 Assets에 추가
  Spacer/Spacer/Assets.xcassets/CommonIcons/CafePeopleIcon.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/CommonIcons/CafePeopleIcon.imageset/cafePeopleIcon.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/Contents.json
  Spacer/Spacer/Assets.xcassets/CommonIcons/LocationIcon.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/CommonIcons/LocationIcon.imageset/LocationIcon.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/callIcon.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/CommonIcons/callIcon.imageset/callIcon 1.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/callIcon.imageset/callIcon 2.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/callIcon.imageset/callIcon.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/heartIcon.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/CommonIcons/heartIcon.imageset/heartIcon 1.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/heartIcon.imageset/heartIcon 2.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/heartIcon.imageset/heartIcon.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/messageIcon.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/CommonIcons/messageIcon.imageset/messageIcon 1.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/messageIcon.imageset/messageIcon 2.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/messageIcon.imageset/messageIcon.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/tableIcon.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/CommonIcons/tableIcon.imageset/tableIcon 1.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/tableIcon.imageset/tableIcon 2.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/tableIcon.imageset/tableIcon.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/timeIcon.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/CommonIcons/timeIcon.imageset/timeIcon 1.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/timeIcon.imageset/timeIcon 2.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/timeIcon.imageset/timeIcon.png
  Spacer/Spacer/Assets.xcassets/StarRatingIcon.imageset/StarRatingIcon.png
Labels: 🐯 랑, 🎨 Design

#47 [FEAT]/#44 변경된 하이파이에 맞춰 BirthdayCafeView, SearchListView 레이아웃 업데이트
  Spacer/Spacer/Cores/BirthdayCafeView/BirthdayCafeViewController.swift
  Spacer/Spacer/Cores/BirthdayCafeView/PopularCafeTableViewCell.swift
  Spacer/Spacer/Cores/BirthdayCafeView/RecentCafeCollectionViewCell.swift
  Spacer/Spacer/Model/MockParser.swift
  Spacer/Spacer/Views/SearchListView/ResultCollectionViewCell.swift
  Spacer/Spacer/Views/SearchListView/SearchListViewController.swift
Labels: 🐯 오션, 🎨 Design, ⭐️ Feature

#48 [FEAT]/#42 VisualTagView의 Map,Decoration view구현
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer/Assets.xcassets/map.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/map.imageset/map 2.png
  Spacer/Spacer/Assets.xcassets/map.imageset/map 3.png
  Spacer/Spacer/Assets.xcassets/map.imageset/map 4.png
  Spacer/Spacer/Assets.xcassets/mapButtonSelected.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/mapButtonSelected.imageset/mapButtonSelected 1.png
  Spacer/Spacer/Assets.xcassets/mapButtonSelected.imageset/mapButtonSelected 2.png
  Spacer/Spacer/Assets.xcassets/mapButtonSelected.imageset/mapButtonSelected.png
  Spacer/Spacer/Assets.xcassets/mapButtonUnselected.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/mapButtonUnselected.imageset/mapButtonUnselected 1.png
  Spacer/Spacer/Assets.xcassets/mapButtonUnselected.imageset/mapButtonUnselected 2.png
  Spacer/Spacer/Assets.xcassets/mapButtonUnselected.imageset/mapButtonUnselected.png
  Spacer/Spacer/Views/VisualTagView/Buttons/BackButton.swift
  Spacer/Spacer/Views/VisualTagView/Buttons/NextButton.swift
  Spacer/Spacer/Views/VisualTagView/Calendar/CalenderCell/CustomCalenderCell.swift
  Spacer/Spacer/Views/VisualTagView/Calendar/VisualTagCalendarViewController.swift
  Spacer/Spacer/Views/VisualTagView/Category/VisualTagCategoryViewController.swift
  Spacer/Spacer/Views/VisualTagView/GridCell/GridCollectionViewCell.swift
  Spacer/Spacer/Views/VisualTagView/Map/VisualTagMapViewController.swift
  Spacer/Spacer/Views/VisualTagView/PeopleRange/VisualTagPeopleRangeViewController.swift
Labels: 🐯 오션, 🎨 Design, ⭐️ Feature

#53 [FEAT]/#51 VisualTagCategoryView에 사용되는 에셋 추가 및 적용
  Spacer/Spacer/Assets.xcassets/VisualCategory/Contents.json
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryBottle.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryBottle.imageset/visualCategoryBottle 1.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryBottle.imageset/visualCategoryBottle 2.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryBottle.imageset/visualCategoryBottle.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCupHolder.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCupHolder.imageset/visualCategoryCupHolder 1.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCupHolder.imageset/visualCategoryCupHolder 2.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCupHolder.imageset/visualCategoryCupHolder.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCustomCookie.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCustomCookie.imageset/visualCategoryCustomCookie 1.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCustomCookie.imageset/visualCategoryCustomCookie 2.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCustomCookie.imageset/visualCategoryCustomCookie.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCustomReceipt.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCustomReceipt.imageset/visualCategoryCustomReceipt 1.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCustomReceipt.imageset/visualCategoryCustomReceipt 2.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCustomReceipt.imageset/visualCategoryCustomReceipt.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCutout.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCutout.imageset/visualCategoryCutout 1.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCutout.imageset/visualCategoryCutout 2.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryCutout.imageset/visualCategoryCutout.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryExhibitionArea.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryExhibitionArea.imageset/visualCategoryExhibitionArea 1.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryExhibitionArea.imageset/visualCategoryExhibitionArea 2.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryExhibitionArea.imageset/visualCategoryExhibitionArea.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryFrame.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryFrame.imageset/visualCategoryFrame 1.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryFrame.imageset/visualCategoryFrame 2.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryFrame.imageset/visualCategoryFrame.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryHBanner.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryHBanner.imageset/visualCategoryHBanner 1.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryHBanner.imageset/visualCategoryHBanner 2.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryHBanner.imageset/visualCategoryHBanner.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryPhotoCard.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryPhotoCard.imageset/visualCategoryPhotoCard 1.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryPhotoCard.imageset/visualCategoryPhotoCard 2.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryPhotoCard.imageset/visualCategoryPhotoCard.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryPhotoZone.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryPhotoZone.imageset/visualCategoryPhotoZone 1.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryPhotoZone.imageset/visualCategoryPhotoZone 2.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryPhotoZone.imageset/visualCategoryPhotoZone.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryVideoShow.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryVideoShow.imageset/visualCategoryVideoShow 1.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryVideoShow.imageset/visualCategoryVideoShow 2.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryVideoShow.imageset/visualCategoryVideoShow.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryXBanner.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryXBanner.imageset/visualCategoryXBanner 1.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryXBanner.imageset/visualCategoryXBanner 2.png
  Spacer/Spacer/Assets.xcassets/VisualCategory/visualCategoryXBanner.imageset/visualCategoryXBanner.png
  Spacer/Spacer/Views/VisualTagView/EventElements/VisualTagCategoryViewController.swift
Labels: 🐯 오션, 🎨 Design

#54 [FEAT]/#50 SearchListView에서 cell을 터치하여 CafeDetailView로 연결함
  Spacer/Spacer/Cores/BirthdayCafeView/BirthdayCafeViewController.swift
  Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
  Spacer/Spacer/Views/SearchListView/SearchListViewController.swift
  Spacer/Spacer/Views/VisualTagView/Calendar/VisualTagCalendarViewController.swift
Labels: 🐯 오션, ⭐️ Feature

#64 [FEAT] #56 새로운 폰트 및 컬러 extension에 추가
  Spacer/Spacer/Cores/BirthdayCafeView/PopularCafeTableViewCell.swift
  Spacer/Spacer/Cores/BirthdayCafeView/RecentCafeCollectionViewCell.swift
  Spacer/Spacer/Extensions/ColorExtension.swift
  Spacer/Spacer/Extensions/FontExtension.swift
  Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
  Spacer/Spacer/Views/SearchListView/SearchListViewController.swift
  Spacer/Spacer/Views/VisualTagView/Calendar/VisualTagCalendarViewController.swift
  Spacer/Spacer/Views/VisualTagView/Map/VisualTagMapViewController.swift
Labels: 🐯 랑, 🎨 Design

#66 [FEAT] #56 스크롤한 정도에 따라 navigationBar와 bottomBar 상태 변경
  Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
Labels: 🐯 랑, ⭐️ Feature

#67 [FEAT] #57 새로운 폰트 사이즈 추가 후 CafeDetailView 폰트 변경 및 CategoryInfomationLineView label text color 변경
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer/Extensions/FontExtension.swift
  Spacer/Spacer/Fonts/esamanru OTF Medium.otf
  Spacer/Spacer/Info.plist
  Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
  Spacer/Spacer/Views/CafeDetailView/CategoryInfomationLineView.swift
  Spacer/Spacer/Views/CafeDetailView/DetailInfomationViewController.swift
Labels: 🐯 랑, 🎨 Design

#69 [FEAT] #63 RequestView 삭제 및 TabBar에 shadow 설정
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer/Cores/MainTabBarViewController.swift
  Spacer/Spacer/Cores/RequestView/RequestViewController.swift
Labels: 🐯 랑, ⭐️ Feature

#68 [FEAT]/#35 SimpleTagView UI구현 및 SearchListView와 데이터 연결
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Spacer/Spacer/Cores/BirthdayCafeView/BirthdayCafeViewController.swift
  Spacer/Spacer/Views/SearchListView/CustomButtonView.swift
  Spacer/Spacer/Views/SearchListView/SearchListViewController.swift
  Spacer/Spacer/Views/SimpleTagView/SimpleTagCollectionViewCell.swift
  Spacer/Spacer/Views/SimpleTagView/SimpleTagViewController.swift
  Spacer/Spacer/Views/VisualTagView/Calendar/CalenderCell/CustomCalenderCell.swift
  Spacer/Spacer/Views/VisualTagView/Calendar/VisualTagCalendarViewController.swift
  Spacer/Spacer/Views/VisualTagView/EventElements/VisualTagCategoryViewController.swift
  Spacer/Spacer/Views/VisualTagView/GridCell/GridCollectionViewCell.swift
Labels: 🐯 오션, ⭐️ Feature

#71 [FEAT]/#70 BirthdayCafeView에서 최근 카페 후기 부분 임시로 막음
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer/Cores/BirthdayCafeView/BirthdayCafeViewController.swift
  Spacer/Spacer/Cores/BirthdayCafeView/ReviewUnderConstructionTableViewCell.swift
Labels: 🐯 오션, 🎨 Design

#72 [STYLE] Change Assets HeaderView in BirthdayCafeView
  Spacer/Spacer/Assets.xcassets/TagBanner.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/TagBanner.imageset/RecCaf 1.png
  Spacer/Spacer/Assets.xcassets/TagBanner.imageset/RecCaf.png
  Spacer/Spacer/Assets.xcassets/TagBanner.imageset/RecCaf2.png
  Spacer/Spacer/Assets.xcassets/TagBanner.imageset/TagBanner 1.png
  Spacer/Spacer/Assets.xcassets/TagBanner.imageset/TagBanner 2.png
  Spacer/Spacer/Assets.xcassets/TagBanner.imageset/TagBanner.png
Labels: 🐯 오션, 🎨 Design

#82 [Feat]/#81 LaunchScreen 구현
  Spacer/Spacer/Assets.xcassets/Launchscreen/Contents.json
  Spacer/Spacer/Assets.xcassets/Launchscreen/LauchIcon.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/Launchscreen/LauchIcon.imageset/LauchIcon.png
  Spacer/Spacer/Assets.xcassets/Launchscreen/LaunchBackground.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/Launchscreen/LaunchBackground.imageset/LaunchBackground.png
  Spacer/Spacer/Assets.xcassets/Launchscreen/LaunchParticle.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/Launchscreen/LaunchParticle.imageset/LaunchParticle.png
  Spacer/Spacer/Assets.xcassets/Launchscreen/LaunchTeamLogo.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/Launchscreen/LaunchTeamLogo.imageset/LaunchTeamLogo.png
  Spacer/Spacer/Base.lproj/LaunchScreen.storyboard
Labels: 🐯 앤더스, ⭐️ Feature

#77 [DOCS]/#76 설정창에 라이선스 확인 섹션 추가
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer/Settings.bundle/FSCalendarDescription.plist
  Spacer/Spacer/Settings.bundle/Licenses.plist
  Spacer/Spacer/Settings.bundle/Root.plist
  Spacer/Spacer/Settings.bundle/en.lproj/Root.strings
  Spacer/Spacer/Settings.bundle/realm-swiftDescription.plist
Labels: 🐯 오션, ⚙️ Setting

#75 [FEAT]/#60 MyPageView구현
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer/Assets.xcassets/MyPage/Contents.json
  Spacer/Spacer/Assets.xcassets/MyPage/anders.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/MyPage/anders.imageset/anders 1.png
  Spacer/Spacer/Assets.xcassets/MyPage/anders.imageset/anders 2.png
  Spacer/Spacer/Assets.xcassets/MyPage/anders.imageset/anders.png
  Spacer/Spacer/Assets.xcassets/MyPage/emailIcon.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/MyPage/emailIcon.imageset/emailIcon 1.png
  Spacer/Spacer/Assets.xcassets/MyPage/emailIcon.imageset/emailIcon 2.png
  Spacer/Spacer/Assets.xcassets/MyPage/emailIcon.imageset/emailIcon.png
  Spacer/Spacer/Assets.xcassets/MyPage/feedBack.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/MyPage/feedBack.imageset/feedBack 1.png
  Spacer/Spacer/Assets.xcassets/MyPage/feedBack.imageset/feedBack 2.png
  Spacer/Spacer/Assets.xcassets/MyPage/feedBack.imageset/feedBack.png
  Spacer/Spacer/Assets.xcassets/MyPage/githubIcon.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/MyPage/githubIcon.imageset/githubIcon 1.png
  Spacer/Spacer/Assets.xcassets/MyPage/githubIcon.imageset/githubIcon 2.png
  Spacer/Spacer/Assets.xcassets/MyPage/githubIcon.imageset/githubIcon.png
  Spacer/Spacer/Assets.xcassets/MyPage/hoaxer.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/MyPage/hoaxer.imageset/hoaxer 1.png
  Spacer/Spacer/Assets.xcassets/MyPage/hoaxer.imageset/hoaxer 2.png
  Spacer/Spacer/Assets.xcassets/MyPage/hoaxer.imageset/hoaxer.png
  Spacer/Spacer/Assets.xcassets/MyPage/linkedInIcon.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/MyPage/linkedInIcon.imageset/linkedInIcon 1.png
  Spacer/Spacer/Assets.xcassets/MyPage/linkedInIcon.imageset/linkedInIcon 2.png
  Spacer/Spacer/Assets.xcassets/MyPage/linkedInIcon.imageset/linkedInIcon.png
  Spacer/Spacer/Assets.xcassets/MyPage/members.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/MyPage/members.imageset/members 1.png
  Spacer/Spacer/Assets.xcassets/MyPage/members.imageset/members 2.png
  Spacer/Spacer/Assets.xcassets/MyPage/members.imageset/members.png
  Spacer/Spacer/Assets.xcassets/MyPage/ocean.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/MyPage/ocean.imageset/ocean 1.png
  Spacer/Spacer/Assets.xcassets/MyPage/ocean.imageset/ocean 2.png
  Spacer/Spacer/Assets.xcassets/MyPage/ocean.imageset/ocean.png
  Spacer/Spacer/Assets.xcassets/MyPage/preparingMyPage.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/MyPage/preparingMyPage.imageset/preparingMyPage 1.png
  Spacer/Spacer/Assets.xcassets/MyPage/preparingMyPage.imageset/preparingMyPage 2.png
  Spacer/Spacer/Assets.xcassets/MyPage/preparingMyPage.imageset/preparingMyPage.png
  Spacer/Spacer/Assets.xcassets/MyPage/rang.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/MyPage/rang.imageset/rang 1.png
  Spacer/Spacer/Assets.xcassets/MyPage/rang.imageset/rang 2.png
  Spacer/Spacer/Assets.xcassets/MyPage/rang.imageset/rang.png
  Spacer/Spacer/Assets.xcassets/MyPage/registerCafe.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/MyPage/registerCafe.imageset/registerCafe 1.png
  Spacer/Spacer/Assets.xcassets/MyPage/registerCafe.imageset/registerCafe 2.png
  Spacer/Spacer/Assets.xcassets/MyPage/registerCafe.imageset/registerCafe.png
  Spacer/Spacer/Assets.xcassets/MyPage/sasha.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/MyPage/sasha.imageset/sasha 1.png
  Spacer/Spacer/Assets.xcassets/MyPage/sasha.imageset/sasha 2.png
  Spacer/Spacer/Assets.xcassets/MyPage/sasha.imageset/sasha.png
  Spacer/Spacer/Cores/MyPageView/IconLabelView.swift
  Spacer/Spacer/Cores/MyPageView/MemberCollectionViewCell.swift
  Spacer/Spacer/Cores/MyPageView/MembersViewController.swift
  Spacer/Spacer/Cores/MyPageView/MyPageTableViewCell.swift
  Spacer/Spacer/Cores/MyPageView/MyPageViewController.swift
Labels: 🐯 오션, 🎨 Design, ⭐️ Feature

#74 [FEAT]/#73 FavoriteView UI구현 및 CafeDetailView와 연결
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Spacer/Spacer/Assets.xcassets/BackButton.imageset/BackButton 1.png
  Spacer/Spacer/Assets.xcassets/BackButton.imageset/BackButton 2.png
  Spacer/Spacer/Assets.xcassets/BackButton.imageset/BackButton.png
  Spacer/Spacer/Assets.xcassets/BackButton.imageset/Contents.json
  Spacer/Spacer/Model/RealmManager.swift
  Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
  Spacer/Spacer/Views/FavoriteView/FavoriteViewController.swift
  Spacer/Spacer/Views/SearchListView/SearchListViewController.swift
  Spacer/Spacer/Views/VisualTagView/EventElements/VisualTagCategoryViewController.swift
Labels: 🐯 오션, ⭐️ Feature

#80 [Feat]/#79 맞춤형카페 찾기 버튼, 네비게이션바 수정 in BirthdayCafeView
  Spacer/Spacer/Cores/BirthdayCafeView/BirthdayCafeViewController.swift
  Spacer/Spacer/Cores/BirthdayCafeView/MyHeaderView.swift
  Spacer/Spacer/Cores/BirthdayCafeView/RecentCafeCollectionViewCell.swift
  Spacer/Spacer/Views/SearchListView/ResultCollectionViewCell.swift
Labels: 🐯 오션, 🎨 Design

#84 [FEAT]/#83 Enable PopGesture in SearchListView
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer/Cores/BirthdayCafeView/BirthdayCafeViewController.swift
  Spacer/Spacer/Cores/MyPageView/MembersViewController.swift
  Spacer/Spacer/Cores/MyPageView/MyPageViewController.swift
  Spacer/Spacer/Extensions/UINavigationControllerExtension.swift
Labels: 🐯 오션, ⭐️ Feature

#87 [FEAT] #61 API 요청하여 받은 데이터 전체 뷰에 적용
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer/Cores/BirthdayCafeView/BirthdayCafeViewController.swift
  Spacer/Spacer/Cores/BirthdayCafeView/PopularCafeTableViewCell.swift
  Spacer/Spacer/Cores/MyPageView/MyPageViewController.swift
  Spacer/Spacer/Managers/APICaller.swift
  Spacer/Spacer/Model/CafeData.swift
  Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
  Spacer/Spacer/Views/CafeDetailView/CategoryInfomationLineView.swift
  Spacer/Spacer/Views/CafeDetailView/DetailInfomationViewController.swift
  Spacer/Spacer/Views/FavoriteView/FavoriteViewController.swift
  Spacer/Spacer/Views/SearchListView/ResultCollectionViewCell.swift
  Spacer/Spacer/Views/SearchListView/SearchListViewController.swift
  Spacer/Spacer/Views/SimpleTagView/SimpleTagViewController.swift
  Spacer/Spacer/Views/VisualTagView/Map/VisualTagMapViewController.swift
Labels: 🐯 랑, 🌐 API, ⭐️ Feature

#93 [Fix] #91 세로로 스크롤했을 때 현재 카페 이미지 번호가 1로 바뀌는 현상 수정
  Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
Labels: 👾 Bug, 🐯 랑
