Repository DeveloperAcademy-POSTECH/MacC-Team-Spacer, pull requests merged in 2022-12, with the labels that each got.

#104 [Fix] #96 상세정보 뷰에서 pageController 스와이프를 이용한 세그먼트 이동 막기
  Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
Labels: 🐯 랑, ⭐️ Feature

#97 [Fix]/#90 Disable tap pageController in OnBoardingPage
  Spacer/Spacer/Views/OnBoardingView/OnBoardingPageViewController.swift
Labels: 👾 Bug, 🐯 오션

#98 [Fix]/#94 CafeDetailView, SearchListView에서 back하였을 경우 네비게이션바가 먼저 hidden처리되는 오류해결
  Spacer/Spacer/Cores/BirthdayCafeView/BirthdayCafeViewController.swift
Labels: 👾 Bug, 🐯 오션

#99 [Fix]/#89 BirthdayCafeView의 오토레이아웃 디버그 해결, SimpleTagView 폰트 적용
  Spacer/Spacer/Cores/BirthdayCafeView/BirthdayCafeViewController.swift
  Spacer/Spacer/Views/SimpleTagView/SimpleTagCollectionViewCell.swift
  Spacer/Spacer/Views/SimpleTagView/SimpleTagViewController.swift
Labels: 👾 Bug, 🐯 오션, 🎨 Design

#101 [Fix]/#100 내일 날짜를 기준으로 캘린더를 설정
  Spacer/Spacer/Views/SimpleTagView/SimpleTagViewController.swift
  Spacer/Spacer/Views/VisualTagView/Calendar/VisualTagCalendarViewController.swift
Labels: 👾 Bug, 🐯 오션

#103 [FEAT] #95 Modify UINavigationController Extension
  Spacer/Spacer/Extensions/UINavigationControllerExtension.swift
  Spacer/Spacer/Views/SearchListView/SearchListViewController.swift
Labels: 🐯 랑, ⭐️ Feature

#107 [Feat]/#106 MainTabBar에 내 보관함(FavoriteView) 추가
  Spacer/Spacer/Assets.xcassets/MagnifyingGlass.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/MagnifyingGlass.imageset/MagnifyingGlass 1.png
  Spacer/Spacer/Assets.xcassets/MagnifyingGlass.imageset/MagnifyingGlass 2.png
  Spacer/Spacer/Assets.xcassets/MagnifyingGlass.imageset/MagnifyingGlass.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/Heart_Fill.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/TabBarIcon/Heart_Fill.imageset/Heart_Fill 1.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/Heart_Fill.imageset/Heart_Fill 2.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/Heart_Fill.imageset/Heart_Fill.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/Heart_Outline.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/TabBarIcon/Heart_Outline.imageset/Heart_Outline 1.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/Heart_Outline.imageset/Heart_Outline 2.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/Heart_Outline.imageset/Heart_Outline.png
  Spacer/Spacer/Cores/BirthdayCafeView/BirthdayCafeViewController.swift
  Spacer/Spacer/Cores/MainTabBarViewController.swift
  Spacer/Spacer/Views/SearchListView/SearchListViewController.swift
Labels: 🐯 오션, ⭐️ Feature

#111 [Feat]/#105 Add Favorite cafe by URL in FavoriteView
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Spacer/Spacer/Assets.xcassets/LinkURL.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/LinkURL.imageset/LinkURL 1.png
  Spacer/Spacer/Assets.xcassets/LinkURL.imageset/LinkURL 2.png
  Spacer/Spacer/Assets.xcassets/LinkURL.imageset/LinkURL.png
  Spacer/Spacer/Assets.xcassets/MyFavorite.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/MyFavorite.imageset/MyFavorite 1.png
  Spacer/Spacer/Assets.xcassets/MyFavorite.imageset/MyFavorite 2.png
  Spacer/Spacer/Assets.xcassets/MyFavorite.imageset/MyFavorite.png
  Spacer/Spacer/Cores/BirthdayCafeView/RecentCafeTableViewCell.swift
  Spacer/Spacer/Model/RealmManager.swift
  Spacer/Spacer/Views/FavoriteView/AddCafeURLViewController.swift
  Spacer/Spacer/Views/FavoriteView/FavoriteViewController.swift
Labels: 👾 Bug, 🐯 오션, 🎨 Design, ⭐️ Feature

#115 [FEAT] #110 make url cafe detail view
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Spacer/Spacer/Views/URLCafeDetailView/URLCafeDetailView.swift
Labels: 🐯 랑, ⭐️ Feature

#118 [FEAT] #116 FavoriteView에 url로 저장한 카페 셀 추가 및 URLCafeDetaiView로 연결
  Spacer/Spacer/Assets.xcassets/CommonIcons/CellLinkURLIcon.imageset/CellLinkURLIcon.png
  Spacer/Spacer/Assets.xcassets/CommonIcons/CellLinkURLIcon.imageset/Contents.json
  Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
  Spacer/Spacer/Views/FavoriteView/FavoriteViewController.swift
  Spacer/Spacer/Views/SearchListView/ResultCollectionViewCell.swift
  Spacer/Spacer/Views/URLCafeDetailView/URLCafeDetailView.swift
Labels: 🐯 랑, ⭐️ Feature
