Repository DeveloperAcademy-POSTECH/MacC-Team-Spacer, pull requests merged in 2022-10, with the labels that each got.

#7 [FEAT] CafeDetailView 하단 예약 버튼 바, 카페 대표 이미지 표시, 상세정보&리뷰 선택 세그먼트 구현
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer/CafeDetailViewController.swift
  Spacer/Spacer/CafeReviewViewController.swift
  Spacer/Spacer/CustomSegmentControl.swift
  Spacer/Spacer/DetailInfomationViewController.swift
Labels: 🐯 랑, ⭐️ Feature

#10 [FEAT] 시스템 가이드 패딩과 폰트 Extension 추가
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer/FontExtension.swift
  Spacer/Spacer/Fonts/Pretendard-Bold.otf
  Spacer/Spacer/Fonts/Pretendard-Medium.otf
  Spacer/Spacer/Fonts/Pretendard-Regular.otf
  Spacer/Spacer/Fonts/Pretendard-SemiBold.otf
  Spacer/Spacer/Fonts/esamanru OTF Bold.otf
  Spacer/Spacer/Info.plist
  Spacer/Spacer/PaddingExtension.swift
Labels: 🐯 오션, ⭐️ Feature, ⚙️ Setting

#12 Feature/#5 make visual tag components
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Spacer/Spacer/FavoriteViewController.swift
  Spacer/Spacer/Fonts/Pretendard-Black.otf
  Spacer/Spacer/Fonts/Pretendard-ExtraBold.otf
  Spacer/Spacer/Fonts/Pretendard-ExtraLight.otf
  Spacer/Spacer/Fonts/Pretendard-Light.otf
  Spacer/Spacer/Fonts/Pretendard-Thin.otf
  Spacer/Spacer/MainTabBarViewController.swift
  Spacer/Spacer/Podfile
  Spacer/Spacer/RequestViewController.swift
  Spacer/Spacer/VisualTagView/BackButton.swift
  Spacer/Spacer/VisualTagView/Calendar/CalenderCell/CustomCalenderCell.swift
  Spacer/Spacer/VisualTagView/Calendar/VisualTagCalendarViewController.swift
  Spacer/Spacer/VisualTagView/CancelButton.swift
  Spacer/Spacer/VisualTagView/Map/VisualTagMapViewController.swift
  Spacer/Spacer/VisualTagView/NextButton.swift
  Spacer/Spacer/VisualTagView/PeopleRange/VisualTagPeopleRangeViewController.swift
  Spacer/Spacer/VisualTagView/PeopleTarget/VisualTagPeopleTargetViewController.swift
Labels: 🐯 혹서, ⭐️ Feature

#18 [Feat] #8 PageViewController와 SegmentedControl 연결
  Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
  Spacer/Spacer/Views/CafeDetailView/CustomSegmentControl.swift
Labels: 🐯 랑, ⭐️ Feature

#20 [Feat] #11 BirthdayCafeView와 관련된 레이아웃 설정
  Spacer/Spacer.xcodeproj/project.pbxproj
  Spacer/Spacer.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Spacer/Spacer/Assets.xcassets/CELEBER_Logo.imageset/CELEBER 1.png
  Spacer/Spacer/Assets.xcassets/CELEBER_Logo.imageset/CELEBER 2.png
  Spacer/Spacer/Assets.xcassets/CELEBER_Logo.imageset/CELEBER.png
  Spacer/Spacer/Assets.xcassets/CELEBER_Logo.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/TagBanner.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/TagBanner.imageset/RecCaf 1.png
  Spacer/Spacer/Assets.xcassets/TagBanner.imageset/RecCaf.png
  Spacer/Spacer/Assets.xcassets/TagBanner.imageset/RecCaf2.png
  Spacer/Spacer/Cores/BirthdayCafeView/BirthdayCafeTableViewSectionHeader.swift
  Spacer/Spacer/Cores/BirthdayCafeView/BirthdayCafeViewController.swift
  Spacer/Spacer/Cores/BirthdayCafeView/MyHeaderView.swift
  Spacer/Spacer/Cores/BirthdayCafeView/PopularCafeTableViewCell.swift
  Spacer/Spacer/Cores/BirthdayCafeView/RecentCafeCollectionViewCell.swift
  Spacer/Spacer/Cores/BirthdayCafeView/RecentCafeTableViewCell.swift
  Spacer/Spacer/Cores/MainTabBarViewController.swift
  Spacer/Spacer/Extensions/PaddingExtension.swift
  Spacer/Spacer/Model/DummyData.json
  Spacer/Spacer/Model/MockParser.swift
Labels: 🐯 오션, ⭐️ Feature

#29 [REFACTOR] #27 refactor cafedetailview group
  Spacer/Spacer/Model/CafeInfoModel.swift
  Spacer/Spacer/Views/CafeDetailView/CafeBasicInfoView.swift
  Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
  Spacer/Spacer/Views/CafeDetailView/DetailInfomationViewController.swift
  Spacer/Spacer/Views/CafeDetailView/InfomationImageAndText.swift
Labels: ⚒️ Refactor, 🐯 랑, ⭐️ Feature, 💾 Data

#30 [FEAT] BirthdayCafeView의 '최근 카페 후기' 셀 터치시 CafeDetailView로 연결 , TabBar이미지 추가
  Spacer/Spacer/Assets.xcassets/TabBarIcon/BirthdayCafe_Fill.imageset/BirthdayCafe_Fill 1.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/BirthdayCafe_Fill.imageset/BirthdayCafe_Fill 2.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/BirthdayCafe_Fill.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/TabBarIcon/BirthdayCafe_Outline.imageset/BirthdayCafe_Outline 1.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/BirthdayCafe_Outline.imageset/BirthdayCafe_Outline 2.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/BirthdayCafe_Outline.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/TabBarIcon/MyPage_Fill.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/TabBarIcon/MyPage_Fill.imageset/MyPage_Fill 1.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/MyPage_Fill.imageset/MyPage_Fill 2.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/MyPage_Outline.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/TabBarIcon/MyPage_Outline.imageset/MyPage_Outline 1.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/MyPage_Outline.imageset/MyPage_Outline 2.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/Request_Fill.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/TabBarIcon/Request_Fill.imageset/Request_Fill 1.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/Request_Fill.imageset/Request_Fill 2.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/Request_Outline.imageset/Contents.json
  Spacer/Spacer/Assets.xcassets/TabBarIcon/Request_Outline.imageset/Request_Outline 1.png
  Spacer/Spacer/Assets.xcassets/TabBarIcon/Request_Outline.imageset/Request_Outline 2.png
  Spacer/Spacer/Cores/BirthdayCafeView/BirthdayCafeViewController.swift
  Spacer/Spacer/Cores/BirthdayCafeView/RecentCafeTableViewCell.swift
  Spacer/Spacer/Cores/MainTabBarViewController.swift
  Spacer/Spacer/Cores/RequestView/RequestViewController.swift
  Spacer/Spacer/Info.plist
  Spacer/Spacer/Views/SearchListView/SearchListViewController.swift
Labels: 🐯 오션

#34 [Design] SearchListView의 searchBar 밑줄 색상 변경
  Spacer/Spacer/Views/SearchListView/SearchListViewController.swift
Labels: 🐯 오션, 🎨 Design

#36 [Feat] #31 cafedetailview tabbar navigationbar setting
  Spacer/Spacer/Cores/BirthdayCafeView/BirthdayCafeViewController.swift
  Spacer/Spacer/Views/CafeDetailView/CafeDetailViewController.swift
Labels: 🐯 랑, ⭐️ Feature
